# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # python specific hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [--no-cache, --config=./ruff.toml]
      - id: ruff
        alias: ruff-isort
        name: ruff-isort
        args: [--fix, --select=I, --no-cache, --config=./ruff.toml]
      - id: ruff-format
        args: [--no-cache, --config=./ruff.toml]