from . import extras
from .__version__ import __version__
from .async_client import AsyncClient
from .client import Client
from .prerecorded.v2 import AsyncTranscriber, AsyncTranscript
from .sync import SyncTranscriber
from .transcriber import Transcriber, Transcript, TranscriptGroup
from .types import (
    AssemblyAIError,
    AutohighlightResponse,
    AutohighlightResult,
    Chapter,
    ContentSafetyLabel,
    ContentSafetyLabelResult,
    ContentSafetyResponse,
    ContentSafetySeverityScore,
    CustomFormattingRequest,
    CustomFormattingResponse,
    Entity,
    EntityType,
    IABLabelResult,
    IABResponse,
    IABResult,
    KeytermsPromptOptions,
    LanguageCode,
    LanguageDetectionOptions,
    ListTranscriptParameters,
    ListTranscriptResponse,
    PageDetails,
    Paragraph,
    PIIRedactedAudioMethod,
    PIIRedactedAudioQuality,
    PIIRedactionPolicy,
    PIISubstitutionPolicy,
    RawTranscriptionConfig,
    RedactPiiAudioOptions,
    Sentence,
    Sentiment,
    SentimentType,
    Settings,
    SpeakerIdentificationRequest,
    SpeakerIdentificationResponse,
    SpeakerOptions,
    SpeakerType,
    SpeechModel,
    SpeechUnderstandingFeatureRequests,
    SpeechUnderstandingFeatureResponses,
    SpeechUnderstandingRequest,
    SpeechUnderstandingResponse,
    StatusResult,
    SummarizationModel,
    SummarizationType,
    SyncSpeechModel,
    SyncTranscriptError,
    SyncTranscriptionConfig,
    SyncTranscriptResponse,
    SyncWord,
    Timestamp,
    TranscriptError,
    TranscriptionConfig,
    TranscriptItem,
    TranscriptMetadata,
    TranscriptStatus,
    TranslationRequest,
    TranslationResponse,
    Utterance,
    UtteranceWord,
    Word,
    WordBoost,
    WordSearchMatch,
)

settings = Settings()
"""Global settings object that applies to all classes that use the `Client` class."""


__all__ = [
    # types
    "AssemblyAIError",
    "AsyncClient",
    "AsyncTranscriber",
    "AsyncTranscript",
    "AutohighlightResponse",
    "AutohighlightResult",
    "Chapter",
    "Client",
    "ContentSafetyLabel",
    "ContentSafetyLabelResult",
    "ContentSafetyResponse",
    "ContentSafetySeverityScore",
    "CustomFormattingRequest",
    "CustomFormattingResponse",
    "Entity",
    "EntityType",
    "IABLabelResult",
    "IABResponse",
    "IABResult",
    "KeytermsPromptOptions",
    "LanguageCode",
    "LanguageDetectionOptions",
    "ListTranscriptParameters",
    "ListTranscriptResponse",
    "PageDetails",
    "Sentence",
    "Sentiment",
    "SentimentType",
    "Settings",
    "SpeakerIdentificationRequest",
    "SpeakerIdentificationResponse",
    "SpeakerOptions",
    "SpeakerType",
    "SpeechModel",
    "SpeechUnderstandingFeatureRequests",
    "SpeechUnderstandingFeatureResponses",
    "SpeechUnderstandingRequest",
    "SpeechUnderstandingResponse",
    "StatusResult",
    "SummarizationModel",
    "SummarizationType",
    "SyncSpeechModel",
    "SyncTranscriber",
    "SyncTranscriptError",
    "SyncTranscriptionConfig",
    "SyncTranscriptResponse",
    "SyncWord",
    "Timestamp",
    "Transcriber",
    "TranscriptionConfig",
    "Transcript",
    "TranscriptError",
    "TranscriptMetadata",
    "TranscriptGroup",
    "TranscriptItem",
    "TranslationRequest",
    "TranslationResponse",
    "TranscriptStatus",
    "Utterance",
    "UtteranceWord",
    "Paragraph",
    "PIIRedactedAudioMethod",
    "PIIRedactedAudioQuality",
    "PIISubstitutionPolicy",
    "PIIRedactionPolicy",
    "RedactPiiAudioOptions",
    "RawTranscriptionConfig",
    "Word",
    "WordBoost",
    "WordSearchMatch",
    # package globals
    "settings",
    # packages
    "extras",
    # version
    "__version__",
]
